name: card_link_pro
description: Digital business card with share and bank shortcuts
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core + UI
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Sharing / files / QR / PDF
  share_plus: ^10.0.2
  qr_flutter: ^4.1.0
  pdf: ^3.11.0
  printing: ^5.13.4

  # Media pickers & color
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0

  # Removed android_intent_plus because we now use only url_launcher
  # for bank app deep links.  See lib/services/bank_launcher.dart for details.

  # Device contacts and permissions
  # Use flutter_contacts for reading/writing contacts on both Android and iOS.
  flutter_contacts: ^1.1.9+2
  # permission_handler is still used by other parts of the app (e.g. camera)
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # Avatars (3)
    - assets/images/avatars/alkhadi.png
    - assets/images/avatars/mariatou.png
    - assets/images/avatars/avatar_business.png
    # Backgrounds (7)
    - assets/images/backgrounds/amz.jpg
    - assets/images/backgrounds/abstract_wave.jpg
    - assets/images/backgrounds/gradient_sky.jpg
    - assets/images/backgrounds/gradient_sand.jpg
    - assets/images/backgrounds/pattern_dots.jpg
    - assets/images/backgrounds/texture_paper.jpg
    - assets/images/backgrounds/city_soft.jpg
    # Legacy background names used by older widgets
    - assets/backgrounds/bg1.jpg
    - assets/backgrounds/bg2.jpg
    - assets/backgrounds/bg3.jpg
